### ISSUE TITLE
Spirit upgrade not work

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#12]
`Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server
user@HomePC:~/spirit$ ./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

INFO checking your license...
ERRO RPC: you have the latest version: v1.23`
The license has been purchased and is active until January 20

**Comment by theaog** [comment]
fixed, thank you for reporting!
