### ISSUE TITLE
spirit ms issues w/ scanning `us` range

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#14]
i cant go for US range .. 

./spirit ms --country us --ports 22 a

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.23) upgrade by 19 Jan 23 00:00 UTC

INFO checking your license...
FAIL: range too big, need confirmation
 [hint] to prevent acccidents, at least one --exclude must be specified
 [hint] use "--exclude 255.255.255.255" as a simple confirmation
ERRO run error exit status 1

=================================

./spirit ms --country us --ports 22 --exclude 255.255.255.255

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.23) upgrade by 19 Jan 23 00:00 UTC

Incorrect Usage: flag provided but not defined: -exclude

NAME:
   spirit masscan - masscan with automatic country zones (default cn)

USAGE:
   ./spirit ms --country cn --ports 22,23,24

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --country value          provide a country name in Alpha-2 CODE (default: "cn")
   --ports value, -p value  comma separated liste of ports: --ports 22,23,24
   --rate value             (default: 50000)
   --help, -h               show help (default: false)
ERRO flag provided but not defined: -exclude

**Comment by theaog** [comment]
what version of masscan are you using? is it maybe an old version that doesn't support the `-exclude` flag?

keep in mind that for `ms` to work, a modern masscan bin should be present in the same folder as spirit.

**Comment by theaog** [comment]
will check about the `us` range, thank you for reporting.

**Comment by giulianopanini99** [comment]
Masscan version 1.0.5 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Jul  8 2019 14:11:13
Compiler: gcc 9.1.0
OS: Linux
CPU: unknown (64 bits)
GIT version: unknown

**Comment by giulianopanini99** [comment]
i think is from your soft :) ,check for me pls

**Comment by theaog** [comment]
1.0.5 is a very old masscan version, please try w/ https://github.com/robertdavidgraham/masscan/releases/tag/1.3.2

and let me know if the issue resolves.

**Comment by giulianopanini99** [comment]
# ./masscan --version

Masscan version 1.3.2 ( https://github.com/robertdavidgraham/masscan )
Compiled on: Jan 17 2023 18:32:11
Compiler: gcc 9.4.0
OS: Linux
CPU: unknown (64 bits)
GIT version: unknown
# ./spirit ms --country us --ports 22 --exclude 255.255.255.255

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.23) upgrade by 19 Jan 23 00:00 UTC

Incorrect Usage: flag provided but not defined: -exclude

NAME:
   spirit masscan - masscan with automatic country zones (default cn)

USAGE:
   ./spirit ms --country cn --ports 22,23,24

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --country value          provide a country name in Alpha-2 CODE (default: "cn")
   --ports value, -p value  comma separated liste of ports: --ports 22,23,24
   --rate value             (default: 50000)
   --help, -h               show help (default: false)
ERRO flag provided but not defined: -exclude

**Comment by theaog** [comment]
thank you, definitely an issue on my side :)
does this happen only w/ US range or also w/ other country codes?

**Comment by giulianopanini99** [comment]
without --exclude other country work ...

**Comment by theaog** [comment]
you don't need to add exclude 255.255.... is already excluded by default w/ spirit

**Comment by giulianopanini99** [comment]
yes , but us need confirmation .. :)

**Comment by theaog** [comment]
hello @giulianopanini99, this should be fixed, please confirm and close the issue.

**Comment by giulianopanini99** [comment]
yes ,works .. thanks a lot !

**Comment by theaog** [comment]
you're very welcome
