### ISSUE TITLE
ARM version issues

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#15]
How do I update the arm version to PRO? I have a purchased license, when I try to register, the PRO version for x86_64 downloads, the version for the ARM remains the free

**Comment by theaog** [comment]
please download the updated arm release: wget https://github.com/theaog/spirit/raw/master/spirit-arm.tgz

let me know if now Pro is enabled

**Comment by Omnividente** [comment]
its OK now

**Comment by theaog** [comment]
super!
