### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#17]
```
[root@vm855696 tmp]# ./spirit register *****

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

INFO checking your license...
ERRO RPC: this server is already licensed

```
```
[root@vm855696 tmp]# ./spirit omni

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit (v1.24) upgrade by 21 Feb 23 00:00 UTC

ERRO omni is not enabled for your license

```

I tried on different x86_64 servers, the version does not become PRO after registration

**Comment by theaog** [comment]
did you have an older license on that server? if yes, do you remember your old license code?

**Comment by Omnividente** [comment]
Yes, older code fa3a8d8de23efe2

вт, 7 февр. 2023 г. в 16:44, aog ***@***.***>:

**Comment by theaog** [comment]
try now

**Comment by Omnividente** [comment]
[image: image.png]

вт, 7 февр. 2023 г. в 16:51, aog ***@***.***>:

**Comment by theaog** [comment]
I don't see the image, is it fixed?

**Comment by Omnividente** [comment]
No
Maybe I answered the first question incorrectly:

Old license (18.12.22-18.01.23) - fa3a8d8de23efe2
The current license is c18177******* (18.01.23-end of February)
ARM Version works in PRO mode, the problem is only with x64_86

**Comment by theaog** [comment]
don't share your current license over here unless you want everybody to use it, delete that :)

**Comment by theaog** [comment]
I deleted your old license from the system.
now register the server w/ the new license and do a spirit upgrade.

**Comment by theaog** [comment]
your 'c18177......' license is not a Pro license, you bought spirit standard.

**Comment by Omnividente** [comment]
Emm. Does Spirit standard not have the features of the Pro version?
I registered the version on arm with the same key, and when I start it, it writes to me that the PRO version

**Comment by Omnividente** [comment]
```
[root@localhost ~]# /usr/spirit/spirit-arm

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.24) upgrade by 09 Feb 23 00:00 UTC

You have new mail in /var/spool/mail/root
[root@localhost ~]# /usr/spirit/spirit-arm omni

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.24) upgrade by 09 Feb 23 00:00 UTC

INFO [MULTI HOST] loading found.lst
FATA open found.lst: no such file or directory
```
Pro function work fine on my c18177... licence in ARM host

**Comment by theaog** [comment]
b/c I opened the ARM version to Pro for any license to promote ARM as it's not much used
x86 you need a Pro version to use Pro features

<img width="968" alt="image" src="https://user-images.githubusercontent.com/100999228/217274977-15e0cf16-ce5f-4560-9eca-426d33232cb6.png">

**Comment by Omnividente** [comment]
I tested all the functions on ARM and thought that the Standard version is PRO, but with a limit of 5 hosts, now everything is clear, then I will buy the PRO version now :)

PS. You need to make tariffs 1 -3-6-12 months :)

**Comment by theaog** [comment]
you think ppl will prefer to buy a longer subscription than to renew monthly?

**Comment by Omnividente** [comment]
Personally, it would be more convenient for me to buy for 3 or 6 months at once

**Comment by theaog** [comment]
ok, thank you for the feedback, I'll work on adding this feature

**Comment by theaog** [comment]
https://github.com/theaog/spirit/issues/18

**Comment by theaog** [comment]
@Omnividente I'm not going to implement this, I've asked my customers and you're the only one wanting more than 1mo at a time.

if you want you can donate extra and I will extend your current key to 3mo or 6mo whatever you prefer.

Pro +3mo: XMR2.8
Pro +6mo: XMR5.6

faster and easier than writing a bunch of code :)
