### ISSUE TITLE
can't run!

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#19]
Hello i just tried to test ... but didnt work! when i run ./spirit ... nothing appears !

**Comment by theaog** [comment]
thank you for reporting, checking what happened in last release

**Comment by Os1r** [comment]
let me know when it will work i want to try...

**Comment by theaog** [comment]
working on it right now

**Comment by Os1r** [comment]
ok thank you!

**Comment by theaog** [comment]
use this until I solve it: wget http://bashupload.com/K6vNE/spirit

**Comment by Os1r** [comment]
thank you i will try now!

**Comment by theaog** [comment]
solved
