### ISSUE TITLE
ERRO RPC: database is locked (5) (SQLITE_BUSY)

### ISSUE THREAD

**Issue by varza1** [theaog/spirit#20]
how can i solve this ?

**Comment by theaog** [comment]
how did you get this error? show me the command you ran

**Comment by theaog** [comment]
should be solved, please check and let me know

**Comment by varza1** [comment]
./spirit register <my key>

**Comment by varza1** [comment]
yep, its working ty

**Comment by theaog** [comment]
thank you for reporting the issue
