### ISSUE TITLE
А very large volume of the spirit file after the update

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#21]
The spirit file has increased in volume by 2 times compared to the last update. Is this definitely not a mistake? (11 mb instead of 5.5 in the previous version)

**Comment by theaog** [comment]
I've updated the language compiler, but it shouldn't have doubled it. Will investigated and let you know, thank you for reporting.

**Comment by theaog** [comment]
hi @Omnividente, this should be solved now bin size is back at `5.6M`. please check w/ an upgrade.

**Comment by Omnividente** [comment]
Yes, everything is OK now, thx
