### ISSUE TITLE
./spirit ms --country cn --ports port / dont work

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#26]
hello .. ./spirit ms --country cn --ports  dont work anymore ..

./spirit ms --country it --ports 22

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.25) upgrade by 12 Mar 23 00:00 UTC

Incorrect Usage: flag provided but not defined: -country

NAME:
   spirit masscan - masscan with automatic country zones (default cn)

USAGE:
   ./spirit ms --zone zone.lst --ports 22,23,24

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --zone value             provide a list of scan zones e.g. 43.224.56.0/22 (default: "zone.lst")
   --ports value, -p value  comma separated liste of ports: --ports 22,23,24
   --rate value             rate for transmitting packets per second (default: 30000)
   --help, -h               show help
ERRO flag provided but not defined: -country

what should i do ?

**Comment by theaog** [comment]
hi @giulianopanini99, please check the changes for v1.25: https://github.com/theaog/spirit/blob/master/CHANGES.md

the website from which I was retrieving updated country zones went down, so I changed the feature for users to input their own `zone.lst` file.

you can quickly google `country zones` and find cidr addresses to put in zone.lst yourself.

**Comment by giulianopanini99** [comment]
try to improve in scan ipinfo.io (ASID) I'll give you something to start if you really want to implement it.. it's very useful.. can you give me a jabber id? to avoid making tickets here?

**Comment by theaog** [comment]
mroot@yax.im
