### ISSUE TITLE
database is locked (5) (SQLITE_BUSY)

### ISSUE THREAD

**Issue by varza1** [theaog/spirit#28]
INFO checking your license...
ERRO RPC: database is locked (5) (SQLITE_BUSY)

how can i fix this ?

**Comment by theaog** [comment]
it's fixed

**Comment by giulianopanini99** [comment]
Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server



  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: you have the latest version: v1.25

**Comment by giulianopanini99** [comment]
on all my server ask me for an upgrade ... but upgrade not exist
