### ISSUE TITLE
ERRO run error exec: no command

### ISSUE THREAD

**Issue by varza1** [theaog/spirit#29]
why i get this error when i do ./spirit forever ? 

INFO
[forever] loop...
INFO [forever] remove temporary files
INFO [step-1] probe open random ports 53322,41422,27022 at rate 30000
ERRO run error exec: no command

**Comment by theaog** [comment]
you always get it?
you get it when you launch it or after some time after it runs a few hours?

are you sure you have masscan in the same folder as spirit?

**Comment by varza1** [comment]
yes i have masscan in the same folder, i get that when i lunch it

**Comment by theaog** [comment]
that error happens when forever is unable to find or run masscan
make sure your user is able to run masscan, check permissions, add +x

**Comment by varza1** [comment]
lol dint work because i dint have zone.lst =)) i put it now and its working now :D

**Comment by theaog** [comment]
cool, I'll add an error message for that then, thank you for letting me know.
