### ISSUE TITLE
upgrade dont work

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#30]
Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server

/ \ / \ / _) Spirit - Pentest Tools
/ ( O )( ( \ github.com/theaog/spirit
_/_/ _/ ___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: you have the latest version: v1.25

**Comment by giulianopanini99** [comment]
on all my server ask me for an upgrade ... but upgrade not exist

**Comment by giulianopanini99** [comment]
the error was fixed ,thanks !

**Comment by theaog** [comment]
you're welcome @giulianopanini99, sorry for the inconvenience.
