### ISSUE TITLE
EXPIRED!

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#34]
Hello bro please fix this issue!

[root@linux .spirit]# ./spirit register ************

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: this server is already licensed
[root@linux .spirit]# ./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: your license key has expired on 2023-03-27 13:59:57.242590732 +0000 UTC
[root@linux .spirit]#

another error 
WARN excluding 34.82.*** [server not licensed]
WARN excluding 119.28.*** [server not licensed]
WARN excluding 116.202.*** [server not licensed]
WARN excluding 79.113.*** [server not licensed]
INFO loaded ip03.txt with 1001 hosts

don't load more than 1000 hosts...and my license is new i buyed yesterday!

**Comment by Os1r** [comment]
i tried several servers...and register..same problem dont load more than 1000 ...

**Comment by theaog** [comment]
It's fixed bro since a couple days ago, when did you get this issue again?

**Comment by theaog** [comment]
Oh I see what you mean, checking now...

**Comment by Os1r** [comment]
ok...waiting

**Comment by theaog** [comment]
done, please try now, should never happen again.

**Comment by Os1r** [comment]
ok i reset all servers..checking now...thank you

**Comment by Os1r** [comment]
[1] Congratulations! Your server has been licensed.
Your license expires on 2023-04-26 08:48:03.057164854 +0000 UTC
ERRO RPC: your server is not licensed:
 Register: $ ./spirit register [key]
 Buy:      $ ./spirit buy

**Comment by theaog** [comment]
It's recommended you do a `./spirit reset` using your old license, when you put a new license on the same server.

**Comment by Os1r** [comment]
i deleted the old license...and i dont have anymore...

**Comment by Os1r** [comment]
i will try on a new server...

**Comment by theaog** [comment]
I deleted all old licenses from the DB, could you check if this change solves the issue?
Please do a reset on old and new license before trying.

**Comment by Os1r** [comment]
done ...thank you! working now on the same servers!

**Comment by theaog** [comment]
awesome! happy it's fixed! thank you for using `spirit`!
