### ISSUE TITLE
Spirit upgrade issue

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#35]
Why is the license renewal always for a random period? For example, I had the last license until April 10, today I made an upgrade and eventually received

`./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Upgrade 100% [====================] (2.7 GB/s)

user@HomePC:~/spirit$ ./spirit

  __    __    ___
 / _\  /  \  / __)   Spirit - Network Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.25) upgrade by 12 Apr 23 00:00 UTC
`
The license lasted only for 2 days and on April 12 I will need to update again

**Comment by theaog** [comment]
hi, is this still an issue?

**Comment by Omnividente** [comment]
Today's update gave 2 weeks, if this continues, then the problem is solved :)

**Comment by NyckBv** [comment]
I have the same problem and it hasn't been solved, does anyone else have the same problem?
./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Network Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: your server is not licensed:
 Register: $ ./spirit register [key]
 Buy:      $ ./spirit buy

**Comment by NyckBv** [comment]
> Today's update gave 2 weeks, if this continues, then the problem is solved :)

Hello. How did you solve the problem? THX

**Comment by theaog** [comment]
you need a license to solve the problem: `./spirit buy`

**Comment by NyckBv** [comment]
### ****Buna si daca nu am xmr sau btc cum pot cumpara ?

**Comment by NyckBv** [comment]
> you need a license to solve the problem: `./spirit buy`

****Buna si daca nu am xmr sau btc cum pot cumpara ?

**Comment by theaog** [comment]
buna @NyckBv, I only accept XMR; nothing else.
