### ISSUE TITLE
spirit upgrade

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#37]
Your license expires on 2023-04-26 08:48:03.057164854 +0000 UTC
ERRO RPC: you have the latest version: v1.25

[root@vps .spirit]# ./spirit

  __    __    ___
 / _\  /  \  / __)   Spirit - Network Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server
[root@vps .spirit]# ./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Network Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

ERRO RPC: you have the latest version: v1.25
[root@vps .spirit]# ./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Network Pentest Tools
/    \(  O )( (_ \   github.com/theaog/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run:

i can't upgrade...

**Comment by Omnividente** [comment]
Same problem. I have Pro version

**Comment by Os1r** [comment]
me too...:(

**Comment by giulianopanini99** [comment]
./spirit upgrade now .. work for me :) try it

**Comment by theaog** [comment]
does this error still persist or was just glitch?

**Comment by Os1r** [comment]
working now!

**Comment by theaog** [comment]
please close issues that you consider resolved
