### ISSUE TITLE
banner have problem

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#39]
I manually checked servers that the banner says are good and are ubuntu or smth else ... but in fact they are miRC servers or other things, they are not OpenSSH

8.213.129.20:921:SSH-2.0-OpenSSH -> is irc
8.213.137.155:1254:SSH-2.0-OpenSSH -> is irc
52.79.113.115:97:SSH-2.0-OpenSSH_5.5p1 Debian-6 -> timeout
43.201.249.158:780:SSH-2.0-OpenSSH_5.9p1 -> timeout

**Comment by theaog** [comment]
I tested banner and don't see any problem w/ it. you're saying it detects mIRC servers as SSH servers? 

the IRC servers return an openssh banner, probably as a way to hide the fact that they're irc servers.
