### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by AndreasTT22** [theaog/spirit#4]
I would like to buy license and instructions for AutoMiner v7
Where can I find it? thanks

**Comment by theaog** [comment]
hi @AndreasTT22 you can buy your license directly via the app:

`./spirit buy` and follow the instructions, make sure to have your Monero wallet open and ready as the app waits for your payment only 10 minutes then it shuts down.

**Comment by AndreasTT22** [comment]
I've just payed but received this : 

ERRO RPC: 5ns elapsed, giving up...

what should I do next?

**Comment by theaog** [comment]
as I said there is a connection timeout of 10 minutes, if it took too long to send the payment the connection might close.

Send me the address you've sent the payment to and an email, and I'll issue your license manually and send it to you.

**Comment by AndreasTT22** [comment]
I've sent to this address : 83h5WwiTuxsKHvU61s7VEX9f4Y6ydufiQTN7G2kaTxnM6iZf8xXEH66N7kgDMeAzK3ddeoQJhfhCLTfDXxHjvkQCUG8PirV

Amount : 1.12176219 XMR

https://blockchair.com/monero/transaction/b161d0e4795b0fa07fbf44e1d37753d780a1534c8b972195833c916c1b439b13

My email : faramilew110@protonmail.com

PS: I'm really interested in AutoMiner. After I get my license, from where I can download it and use it? Thanks

**Comment by theaog** [comment]
email sent!

**Comment by giulianopanini99** [comment]
hello ... i pay and i get ERRO RPC: 5ns elapsed, giving up...

**Comment by giulianopanini99** [comment]
problem fix ,thanks
