### ISSUE TITLE
your license key has expired on 2023-07-01 12:29:28.076217737 +0000 UTC

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#41]
WARN your spirit trial has ended [server not licensed] 
my license should expire on 25.07

**Comment by theaog** [comment]
give me the first 5 digits of your license, I'll check and resolve.

**Comment by giulianopanini99** [comment]
6de82

**Comment by giulianopanini99** [comment]
tell me when is fixed to close issue ,thanks a lot

**Comment by theaog** [comment]
indeed your license expires on 2023-07-25, are you sure the date on your server is correct?
does that happen on any server you try to register w/ this license?

**Comment by giulianopanini99** [comment]
date
Sun 02 Jul 2023 05:04:51 PM CEST

**Comment by giulianopanini99** [comment]
the date is good, it does this on all roots
