### ISSUE TITLE
server not licensed

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#42]
WARN excluded 0 IP from hosts file (server not licensed)

... but i just bought
Spirit Pro (v1.26) upgrade by 17 Jul 23 00:00 UTC

Your license expires on 2023-08-02 10:38:13.645067207 +0000 UTC

**Comment by theaog** [comment]
checking, thank you for reporting

**Comment by theaog** [comment]
should be fixed, please `spirit upgrade` and try again.

**Comment by Os1r** [comment]
now works..thank you!

**Comment by theaog** [comment]
you're welcome, anytime.
