### ISSUE TITLE
what king of license /

### ISSUE THREAD

**Issue by develope2022** [theaog/spirit#43]
Hello , i'm planning to buy license but i don-t know 
Standard $100
Professional $150
what is the difference between these types of license?

**Comment by theaog** [comment]
hello there, please check the HELP (https://github.com/theaog/spirit/blob/master/HELP) 

shows you extra tools available under `2-spirit-pro:`

**Comment by theaog** [comment]
should probably make it more clear in the buy prompt, thank you for letting me know.
