### ISSUE TITLE
key wrong ... why ?

### ISSUE THREAD

**Issue by develope2022** [theaog/spirit#44]
Hello ,  just bought the licence , and now it-s say trial endend and key wrong 
why ?
✔ Professional $150
Starting XMR transaction in 0...
Send 0.98719637 XMR ($150) to address:
 86tU2k8mPBfTDbL4JHrYUeXmtxYsR9EmVgyqMdTYvbCgAhLEhZioTLnVWyEoLXb2oU98KgRorX39CPszHTT7GvouKxzkCsA

waiting for transaction... 25.020908023s
Received 0.98719637 XMR | TransactionID 327236d2311db35fb8da136ff7ad3655cc6c2f63482dbd80e7cb69d2ff44469c

Success! Your license key:

**Comment by theaog** [comment]
you got your license key? to use use it type: `./spirit register <your key>`

**Comment by theaog** [comment]
please download latest spirit from https://github.com/theaog/spirit/releases
and try again

**Comment by theaog** [comment]
you haven't replied, so I assume everything's alright now. I'll close this issue, feel free to reopen it if need be. thank you for using spirit and providing us w/ your support to keep this project going.
