### ISSUE TITLE
ERRO RPC: database is locked (5) (SQLITE_BUSY) 

### ISSUE THREAD

**Issue by develope2022** [theaog/spirit#45]
when i entery key i recive this , and when i do ./spirit upgrade i recive ERRO RPC: your server is not licensed:
the server was licensed, suddenly I get this error

**Comment by Os1r** [comment]
same ...!

**Comment by theaog** [comment]
thank you for reporting, I'm investigating this issue, bear w/ me.

**Comment by theaog** [comment]
should be fixed guys, please confirm and close the issue when all good.
