### ISSUE TITLE
FATA your spirit trial has ended (./spirit buy)

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#48]
fix that bro...! i have buyed my license one week ago!...

**Comment by theaog** [comment]
please just get the new bin from this repo and do `register` then `upgrade` check CHANGES.md
let me know if you experience issues w/ the new version

**Comment by theaog** [comment]
if you still have issues, send me the last 6 digits of your license and I'll check

**Comment by Os1r** [comment]
ok done..working now!

**Comment by theaog** [comment]
awesome! glad to hear! please checkout `$ ./spirit partner`
