### ISSUE TITLE
ERRO RPC: [7] servers out of [7] for plan Pro

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#49]
did you changed from 10 to 7 ... ? that's silly bro!

**Comment by theaog** [comment]
what are the last 6 digits of your license bro?

**Comment by theaog** [comment]
old licenses should still have 10, could you send me your last 6?

**Comment by Os1r** [comment]
> old licenses should still have 10, could you send me your last 6?

last 6 digits -> 319f0b

**Comment by theaog** [comment]
should be fixed, try now and let me know

**Comment by Os1r** [comment]
yes , working now! thanks
