### ISSUE TITLE
ERRO run error exec: no command

### ISSUE THREAD

**Issue by develope2022** [theaog/spirit#5]
Hello , i recive this error ERRO run error exec: no command when i try to use :
./spirit ms --country kr --ports 111,1230
what should i do ?

**Comment by develope2022** [comment]
root@23-vps:~# ./spirit ms --country cn --ports 4022,7722

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/aogspirit/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Spirit Pro (v1.22) upgrade by 10 Nov 22 00:00 UTC

INFO checking your license...
ERRO run error exec: no command
root@23-vps:~#

**Comment by theaog** [comment]
You probably don't have `masscan` in the same folder as `spirit`, can you check and let me know if that was the issue?

**Comment by theaog** [comment]
@develope2022 did you solve the issue?

**Comment by develope2022** [comment]
yes , you are right,  istalling the masscan on server fix the issue
thanks


-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Nov 1, 2022, 01:58 by ***@***.***:

**Comment by theaog** [comment]
no problem buddy, anytime! Thank you for using spirit!
