### ISSUE TITLE
upgrade error!

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#50]
when i try to update i get this error -> ERRO RPC: context deadline exceeded
and TRIAL error also... ERRO running in TRIAL mode: enjoy!
and i'm registered...!

**Comment by theaog** [comment]
please try again

**Comment by theaog** [comment]
if you still have issues, send me your jabberID and I'll reach out to you

**Comment by Os1r** [comment]
i don't knw what you did bro...but with the last update the brute is getting lower in connexions..
Before update the brute was working like a charm now i can max [20]conns...

**Comment by Os1r** [comment]
OsirisOne@jabb.im

**Comment by theaog** [comment]
you sure? let's fix it then
