### ISSUE TITLE
upgrade!

### ISSUE THREAD

**Issue by Os1r** [theaog/spirit#52]
Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server

Upgrade bro...

**Comment by giulianopanini99** [comment]
its fixed

**Comment by Os1r** [comment]
no it's not ! Still can't upgrade!

**Comment by giulianopanini99** [comment]
not fiexd ;)) update came but still with error :) we cannot brute

**Comment by giulianopanini99** [comment]
100%  (473 MB/s) [0s] Upgrade i receive this and i think its fixed :)

**Comment by Os1r** [comment]
still not fixed..! ERRO RPC: you have the latest version: v1.28

**Comment by theaog** [comment]
sorry about that, fixed now

**Comment by theaog** [comment]
please close the issue once the upgrade is successful for you or let me know if you still have an issue.

**Comment by Os1r** [comment]
fixed!
