### ISSUE TITLE
Basic Lifetime

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#54]
You can learn more about the Basic Lifetime license.
Are there any restrictions on the number of hosts?
Is there a time limit?
What functions are active?

**Comment by theaog** [comment]
everything included in the Basic license will be available in Lifetime, the only difference is that you won't have to renew monthly but pay once and have it forever.

Type: `spirit buy` and see the what's included in the Basic license

**Comment by Omnividente** [comment]
And what will happen to the license if the number of servers exceeds 3?

**Comment by theaog** [comment]
You can reset the license as usual using `./spirit reset` and register new servers over and over as you need.

**Comment by theaog** [comment]
If you have a better idea on how to handle licensing for spirit or have more questions, you can reach out to me on XMPP: aog@yax.im
