### ISSUE TITLE
hey bro! i have a problem.

### ISSUE THREAD

**Issue by ipsrulz** [theaog/spirit#55]
hey bro, i just buyed the basic license and it gave me only 3 conn, can u fix it please ? 
ERRO RPC: [3] servers out of [3] for plan Basic
0a3346 this are the last 6 words of the license. thank you!

**Comment by theaog** [comment]
hey there! would you like to upgrade to a Pro license?

**Comment by ipsrulz** [comment]
I dont got enought money for Pro bro, i'm sorry

**Comment by theaog** [comment]
upgraded your license this one time to help you out, please do a `spirit upgrade` and close the issue if all works -- have fun!

**Comment by ipsrulz** [comment]
Awesome, thank you so much!
