### ISSUE TITLE
Is there no free version anymore?

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#58]
Hi. The latest version no longer has a free trial, has the free version been removed or is it a bug?
The lifetime version is also no longer on the lists. Can I buy the lifetime version?

**Comment by theaog** [comment]
Hello, I removed Free because of abuse, if you enjoy spirit please consider donating by getting a license to support the project development.

**Comment by Omnividente** [comment]
Can  i buy lifetime version?

**Comment by theaog** [comment]
sorry, not at the moment -- only monthly versions available
