### ISSUE TITLE
Your license expires on 2022-11-28 

### ISSUE THREAD

**Issue by giulianopanini99** [theaog/spirit#6]
I register, it says that the license is valid, but when I give it commands, it says that the spirit has expired. what happens ?

**Comment by giulianopanini99** [comment]
INFO checking your license...
[2] Congratulations! Your server has been licensed.
Your license expires on 2022-11-28 07:14:53.121140639 +0000 UTC
# ./spirit upgrade

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/aogspirit/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

INFO checking your license...
Upgrade 100% [====================] (165.751 MB/s)

#./spirit brute

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/aogspirit/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run:
$ ./spirit upgrade #on your licensed server

**Comment by theaog** [comment]
thank you for reporting, checking...
will update you soon

**Comment by theaog** [comment]
could you try again? should be working now.
please do a `./spirit upgrade` first

**Comment by giulianopanini99** [comment]
yes ,now works .. but what was the problem ? your license server ?

**Comment by theaog** [comment]
yeah, I got ddosed on the license server, mitigated and scaled up.
happy this is resolved, let me know if you encounter any other issues.

**Comment by giulianopanini99** [comment]
in the future, if you manage to make it possible to remove the license only from certain servers, not remove all

**Comment by theaog** [comment]
it's designed like this, to avoid abuse :)
