### ISSUE TITLE
hey bro, what is going on here ? 

### ISSUE THREAD

**Issue by ipsrulz** [theaog/spirit#67]
i just downloaded it again from github, i upgraded it and still don't work, then he is removing by himself.. wtf ?

root@vmi1664276:/mnt/ban# ./spirit upgrade
  __    __    ___
 / _\  /  \  / __)   The Sword of the Spirit
/    \(  O )( (_ \   Spirit - Network Pentest Tools
\_/\_/ \__/  \___/   github.com/theaog/spirit
Please note that using this software constitutes
your acceptance of our --terms of service.
HINT: Join our Telegram for a chat [t.me/spiritNPT]
 100%  (446 MB/s) [0s] Upgrade
finished in 2.203s
root@vmi1664276:/mnt/ban# ./spirit brute -T 10s --block -t 4000
  __    __    ___
 / _\  /  \  / __)   The Shods of Readiness
/    \(  O )( (_ \   Spirit - Network Pentest Tools
\_/\_/ \__/  \___/   github.com/theaog/spirit
Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries -- just wait a sec...
Auto-upgrade failed...
Download new version from github.com/theaog/spirit
root@vmi1664276:/mnt/ban# ./spirit brute -T 10s --block -t 4000
bash: ./spirit: No such file or directory
root@vmi1664276:/mnt/ban#

**Comment by theaog** [comment]
should be working now. please use telegram channel for issues. faster replies.
