### ISSUE TITLE
Cannot be upgraded

### ISSUE THREAD

**Issue by yanghuajun336** [theaog/spirit#68]
Where is the source code? I may need to recompile it for my environment.
  __    __    ___
 / _\  /  \  / __)   The Shield of Faith
/    \(  O )( (_ \   Spirit - Network Pentest Tools
\_/\_/ \__/  \___/   github.com/theaog/spirit

Please note that using this software constitutes
your acceptance of our --terms of service.

New feature: encrypt your p.lst passfile
  ./spirit encrypt --help
New feature: ultra-banner -- faster code and new Terminal UI
  ./spirit ultra-banner --help

ERRO unable to connect to license server: connection timeout...

**Comment by yanghuajun336** [comment]
ohh It's not open source? - I don't know.

**Comment by ipsrulz** [comment]
yeahh.. 
 100%   [3m57s] [61774/265534]gis:123 Found[0] Hosts[39] Blocked[38] Bruting[1] Conn[2000]
is blocking all the the ip`s too .. come on dude wtf..

**Comment by ipsrulz** [comment]
and u ask money for it ? :)) omfg.

**Comment by yanghuajun336** [comment]
I don't know how to work it? The upgrade failed.

**Comment by ipsrulz** [comment]
100%   [3m57s] [61774/265534]gis:123 Found[0] Hosts[39] Blocked[38] Bruting[1] Conn[4000]
it dont work for nothing, is blocking all the iP`s .. dude.. wtf ?!!

**Comment by theaog** [comment]
if you have any issues, please reach out on telegram support channel.
