### ISSUE TITLE
dude.. u did a new update, and again is not working.. wtf..

### ISSUE THREAD

**Issue by ipsrulz** [theaog/spirit#69]
[root@srv572380989 ban]# ./spirit register
  __    __    ___
 / _\  /  \  / __)   The Shods of Readiness
/    \(  O )( (_ \   Spirit - Network Pentest Tools
\_/\_/ \__/  \___/   github.com/theaog/spirit
Please note that using this software constitutes
your acceptance of our --terms of service.
HINT: Want more accuracy? Use AutoThreads `./spirit brute -A`

Enter license key (secured):
[1] Congratulations! Your server has been licensed.
License expires on Tue, 17 Sep 2024 14:11:39 UTC
 100%  (3.6 GB/s) [0s] Upgrade
finished in 11.337s
[root@srv572380989 ban]# ./spirit brute -T 10s --block -t 2000
  __    __    ___
 / _\  /  \  / __)   The Breastplate of Righteousness
/    \(  O )( (_ \   Spirit - Network Pentest Tools
\_/\_/ \__/  \___/   github.com/theaog/spirit
Please note that using this software constitutes
your acceptance of our --terms of service.
Spirit NPT (9860c) upgrade by 23 Sep 24 00:00 UTC (licensed)
HINT: Use `./spirit passwd` to generate random passwords based on system users
rlimit soft [262144] hard [262144] ($ ulimit -n)
FATA UNLICENSED: ./spirit upgrade
[root@srv572380989 ban]#

**Comment by theaog** [comment]
issue is resolved, sorry for the inconvenience -- I will be adding 5 days to all licenses.
