### ISSUE TITLE
Free licence issues

### ISSUE THREAD

**Issue by Omnividente** [theaog/spirit#8]
Hello. Is the free version limited in time? I am testing this software, but it stopped working on all PCs after a few days (PCs are not connected to the Internet, so spirit without license)
```
[root@localhost spirit]# ./spirit

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/aogspirit/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run: 
$ ./spirit upgrade #on your licensed server

[root@localhost ~]# ./spirit scan --lan

  __    __    ___
 / _\  /  \  / __)   Spirit - Pentest Tools
/    \(  O )( (_ \   github.com/aogspirit/spirit
\_/\_/ \__/  \___/

Please note that using this software constitutes
your acceptance of our --terms of service.

Finally, my brethren,
be strong in the Lord,
and in the power of his might.

Put on the whole armour of God,
that ye may be able to stand against
the wiles of the devil.

Spirit has expired, no worries just run: 
$ ./spirit upgrade #on your licensed server

```

**Comment by theaog** [comment]
yeah, the bin expires and a new one is generated every 15 days, just download the new bin from the this repo, check readme.

**Comment by Omnividente** [comment]
is it possible to purchase a program with a free license, in the current state (without the possibility of updating) without a time bomb? If so, what is the price? :) I need standalone software, without pro functions and license checks.

**Comment by theaog** [comment]
yes, it's possible -- you can purchase the standard version via `./spirit buy` using XMR (Monero)

<img width="538" alt="image" src="https://user-images.githubusercontent.com/100999228/205638082-0f0de286-f88f-4010-8f89-4c430b766814.png">

**Comment by Omnividente** [comment]
Will the standard version work without a time limit and without binding to the host? Or 1 license for 1 host?
Is there a complete list of differences and limitations of standard pro free?

**Comment by theaog** [comment]
https://github.com/theaog/spirit/blob/master/CHANGES.md#spirit-122
spirit can be registered on 5 servers
spirit pro can be registered on 10 servers

if you lose access to the servers you can start fresh w/ `./spirit reset`

the app works for 15 days then it expires, all you have to do every 15 days is type: `./spirit upgrade`

the tools section in the app that will work after expiry forever `./spirit --help`

**Comment by theaog** [comment]
haven't seen a reply in 3 days, will close the issue, if you need anything reopen it.

**Comment by Omnividente** [comment]
100(150) $ every month or a one-time payment for 1 license?
